- name: Deploy CKAN-spatial server
  hosts: ckan_servers
  become: true
  gather_facts: true

  vars_prompt:
    - name: "ansible_become_password"
      prompt: "Enter your sudo password (or press Enter to proceed without a password)"
      private: true
      default: ""

    - name: "user_deployment_version"
      prompt: "Select the deployment version\n 1. Development (Desarrollo)\n 2. Staging (Preproducci贸n)\n 3. Production (Certificaci贸n)\n"
      private: false
      default: "1"

    - name: "setup_local_database"
      prompt: "Do you want to setup a local PostgresSQL Database? \nWARNING: This may delete an existing PostgreSQL database! (y/n)"
      private: false
      default: "n"
      
    - name: "setup_local_solr"
      prompt: "Do you want to setup a local Solr instance with spatial capabilities? (y/n)"
      private: false
      default: "n"

    - name: "setup_local_redis"
      prompt: "Do you want to setup a local Redis instance? (y/n)"
      private: false
      default: "n"

  pre_tasks:
    - name: Verify distribution
      fail:
        msg: "Currently, it only supports CentOS and RedHat distributions."
      when: ansible_distribution | lower not in ['centos', 'redhat']

    - name: Validate user_deployment_version
      fail:
        msg: "Deployment version must be '1', '2', or '3'"
      when: user_deployment_version not in ['1', '2', '3']

    - name: Set deployment version name
      set_fact:
        deployment_version_name: "{% if user_deployment_version == '1' %}Desarrollo{% elif user_deployment_version == '2' %}Preproducci贸n{% elif user_deployment_version == '3' %}Certificaci贸n{% else %}0{% endif %}"

  roles:
      - { role: common, tags: common }
      - { role: database, tags: database, when: setup_local_database == "y" }
      - { role: solr, tags: solr, when: setup_local_solr == "y" }
      - { role: redis, tags: redis, when: setup_local_redis == "y" }
      - { role: ckan, tags: ckan }
      - { role: ckan_pycsw, tags: ckan_pycsw }
      - { role: webserver, tags: webserver }
      - { role: supervisor, tags: supervisor }

  post_tasks:
    - name: "Change owner and group of {{ ckan_virtualenv }} to {{ ckan_user }}"
      file:
        path: "{{ ckan_virtualenv }}"
        owner: "{{ ckan_user }}"
        group: "{{ ckan_group }}"
        recurse: yes
      become: true

    - name: "Change owner and group of {{ ckan_config_dir }} to {{ ckan_user }}"
      file:
        path: "{{ ckan_config_dir }}"
        owner: "{{ ckan_user }}"
        group: "{{ ckan_group }}"
        recurse: yes
      become: true