- name: Deploy CKAN-spatial server
  hosts: ckan_servers
  become: true
  gather_facts: true

  vars_prompt:
    - name: "setup_local_database"
      prompt: "Do you want to setup a local PostgresSQL Database? \nWARNING: This may delete an existing PostgreSQL database! (y/n)"
      private: false
      default: "n"
      
    - name: "setup_local_solr"
      prompt: "Do you want to setup a local Solr instance with spatial capabilities? (y/n)"
      private: false
      default: "n"

    - name: "setup_local_redis"
      prompt: "Do you want to setup a local Redis instance? (y/n)"
      private: false
      default: "n"

    - name: "setup_local_ckan"
      prompt: "Do you want to setup a local CKAN instance? (y/n)"
      private: false
      default: "y"

  pre_tasks:
    - name: Verify distribution
      fail:
        msg: "Currently, it only supports CentOS and RedHat distributions."
      when: ansible_distribution | lower not in ['centos', 'redhat']

  roles:
      - { role: common, tags: common }
      - { role: database, tags: database, when: setup_local_database == "y" }
      - { role: solr, tags: solr, when: setup_local_solr == "y" }
      - { role: redis, tags: redis, when: setup_local_redis == "y" }
      - { role: ckan, tags: ckan, when: setup_local_ckan == "y"  }
      - { role: webserver, tags: webserver }
      #TODO: Fix supervisor RHEL
      #- { role: supervisor, tags: supervisor }
