 

### Ansible connection  #########################################
## If you are running the playbook on the same machine, you can use the "local" connection instead of "ssh"
ansible_connection: local

### Ansible Target host  #########################################
server_name: production
ansible_host: 192.168.68.109
ansible_user: ckan
ansible_port: 8022
ansible_ssh_pass: ckan

### Webserver #########################################
proxy_server_name: localhost
proxy_server_url: http://{{ proxy_server_name }}
proxy_ckan_location: /catalog
proxy_pycsw_location: /csw
pycsw_port: 8000
ckan_port: 5000
nginx_dir: /etc/nginx
nginx_log_dir: /var/log/nginx
nginx_port: 81
nginx_sslport: 8443
proxy_pycsw_proxy_pass: "{{ proxy_server_url }}:{{ pycsw_port }}"
proxy_ckan_proxy_pass: "{{ proxy_server_url }}:{{ ckan_port }}"
# PRODUCTION DISABLE AND USE A BALANCER!: Enable or disable the httpd network connect to avoid nginx proxy_pass issues. https://www.nginx.com/blog/using-nginx-plus-with-selinux/
enable_httpd_network_connect: true
# URLs [ckan, pycsw]
ckan_url: "{{ proxy_server_url }}:{{ ckan_port }}{{ proxy_ckan_location }}"
pycsw_url: "{{ proxy_server_url }}:{{ pycsw_port }}{{ proxy_pycsw_location }}"

### CKAN configuration variables #########################################
ckan_site_id: ckan_test
ckan_site_name: "{{ proxy_server_url }}"
## Check if the ckan_site_url is correctly configured. Default uses the proxy_server_name and nginx_port
ckan_site_url: "{{ ckan_site_name }}:{{ nginx_port }}"
ckan_root_path: "{{ proxy_ckan_location }}/{% raw %}{{LANG}}{% endraw %}"
ckan_site_title: "CKAN Test site"
ckan_site_description: "CKAN site to test Open Data portals."
ckan_sysadmin_name: ckan_admin
ckan_sysadmin_email: ckan_admin@localhost
ckan_sysadmin_password: test1234

#### Views
ckan_views_default_views: "image_view webpage_view text_view recline_view wmts_view geojson_view geo_view shp_view pdf_view" 

#### Plugins
ckan_plugins: "stats text_view image_view webpage_view recline_view resourcedictionary datastore xloader harvest spatial_metadata spatial_query spatial_harvest_metadata_api csw_harvester waf_harvester doc_harvester resource_proxy geo_view geojson_view wmts_view shp_view dcat dcat_rdf_harvester dcat_json_harvester dcat_json_interface schemingdcat_datasets schemingdcat_groups schemingdcat_organizations schemingdcat schemingdcat_ckan_harvester schemingdcat_xls_harvester pdf_view pages fluent"

#### Localization
ckan_locale_default: en
ckan_locale_order: "en es pt_BR ja it cs_CZ ca fr el sv sr sr@latin no sk fi ru de pl nl bg ko_KR hu sa sl lv"
ckan_locales_offered: "en es pt_BR ja it cs_CZ ca fr el sv sr sr@latin no sk fi ru de pl nl bg ko_KR hu sa sl lv"

#### ckanext-dcat
ckanext__dcat__base_uri: "{{ ckan_site_url }}{{ proxy_ckan_location }}"
ckanext__dcat__rdf__profiles: "euro_dcat_ap_2"
ckanext__dcat__catalog_endpoint: "{{ proxy_ckan_location }}.{_format}"

### ckanext-geoview
ckanext__geoview__ol_viewer_formats: "wms wfs geojson gml kml"
ckanext__geoview__geojson__max_file_size: 1000000

### ckanext-scheming
ckanext__scheming__dataset_schemas: "ckanext.schemingdcat:schemas/geodcatap/geodcatap_dataset.yaml"
ckanext__scheming__group_schemas: "ckanext.schemingdcat:schemas/geodcatap_es/geodcatap_es_group.json"
ckanext__scheming__organization_schemas: "ckanext.schemingdcat:schemas/geodcatap_es/geodcatap_es_org.json"
ckanext__scheming__presets: "ckanext.schemingdcat:schemas/default_presets.json ckanext.fluent:presets.json"

### ckanext-schemingdcat
ckanext__schemingdcat__facet_list: "theme groups theme_es dcat_type groups publisher_name publisher_type spatial_uri owner_org res_format frequency tags tag_uri conforms_to"
ckanext__schemingdcat__organization_custom_facets: true
ckanext__schemingdcat__group_custom_facets: true
ckanext__schemingdcat__geometadata_base_uri: "{{ ckan_site_url }}{{ proxy_pycsw_location }}"

#### ckanext-spatial
ckanext__spatial__common_map__custom_url: http://a.tile.openstreetmap.org/{z}/{x}/{y}.png
ckanext__spatial__common_map__attribution: "Map tiles by <a href=\"http://openstreetmap.org\">OpenStreetMap</a> (<a href=\"http://creativecommons.org/licenses/by-sa/3.0\">CC BY SA</a>)"

#### ckanext-xloader
ckanext__xloader__api_token: api_token
ckanext__xloader__jobs_db__uri: "postgresql://{{ ckan_database.ckan_db_user }}:{{ ckan_database.ckan_db_password }}@{{ ckan_database.postgres_host }}/{{ ckan_database.ckan_db }}"


### Services config ###
### pycsw service #########################################
pycsw_enabled: false

### CKAN service #########################################
ckan_version: ckan-2.9.11
ckan_virtualenv: /usr/lib/ckan/default
ckan_config_dir: /etc/ckan/default
ckan_user: ckan
ckan_group: ckan
ckan_pip_constraints: /tmp/ckan_constraints.txt
ckan_storage_dir: "{{ ckan_config_dir }}/storage"
ckan_log_dir: /var/log/ckan
worker_harvester_cron: true
ckan_tmp_dir: /tmp
uwsgi_unix_http_server_socket_path: "{{ ckan_tmp_dir }}/uwsgi.sock"

### CKAN extension versions #########################################
ckanext_versions:
  ckanext_xloader: 1.0.1
  ckanext_harvest: v1.5.6
  ckanext_geoview: v0.1.0
  ckanext_spatial: v2.1.1
  ckanext_dcat: v1.6.0
  ckanext_scheming: release-3.0.0
  ckanext_resourcedictionary: v1.0.1
  ckanext_pages: v0.5.2
  ckanext_pdfview: 0.0.8
  ckanext_fluent: v1.0.1
  ckanext_schemingdcat: v3.0.0

### Database service #########################################
postgres_port: 5432
postgres_dir: "/var/lib/pgsql/data"
ckan_database: {
  postgres_user: "postgres",
  postgres_password: "postgres",
  ckan_db_user: "ckandbuser",
  ckan_db_password: "ckandbpassword",
  ckan_db: "ckan_db",
  postgres_host: "localhost",
}

ckan_datastore: {
  datastore_readonly_user: "datastore_ro",
  datastore_readonly_password: "datastoredbpassword",
  datastore_db: "ckan_datastore",
  datastore_host: "localhost",
}

### Solr Service #########################################
solr_os_supported: 
  - "RedHat"
  - "CentOS"
  - "Debian"
solr_version: 9.5.0
solr_port: 8983
solr_host: 127.0.0.1
solr_mirror: "https://dlcdn.apache.org"
solr_workspace: /root
solr_tmp_dir: /tmp
solr_schema_ckan_branch: "dev-v2.10"
jts_version: 1.19.0
jts_jar_file: "{{ solr_dir }}/server/solr-webapp/webapp/WEB-INF/lib/jts-core-{{ jts_version }}.jar"
solr_user: solr
solr_group: "{{ solr_user }}"
solr_remove_cruft: false
solr_service_manage: true
solr_service_name: solr
solr_ckan_core_name: ckan
solr_service_state: started
solr_config_file: /etc/default/{{ solr_service_name }}.in.sh
solr_install_dir: /opt
solr_dir: "/opt/{{ solr_service_name }}"
solr_data: "/var/{{ solr_service_name }}"
solr_default_core_path: "{% if solr_version.split('.')[0] < '9' %}{{ solr_dir }}/example/files/conf/{% else %}{{ solr_dir }}/server/solr/configsets/_default/conf/{% endif %}"
solr_config_dir: "{{ solr_dir }}/server/solr/configsets"
solr_ckan_schema_file: "{{ solr_data }}/data/ckan/conf/managed-schema.xml"
solr_xms: "256M"
solr_xmx: "1024M"
solr_timezone: "{{ timezone }}"
solr_opts: "$SOLR_OPTS -Dlog4j2.formatMsgNoLookups=true"
# Enable restart solr handler
solr_restart_handler_enabled: true

### Redis Service #########################################
redis_os_supported: 
  - "RedHat"
  - "CentOS"
  - "Debian"
  - "Archlinux"
redis_enablerepo: epel
redis_port: 6379
redis_bind_interface: 127.0.0.1
redis_unixsocket: ''
redis_timeout: 300
redis_loglevel: "notice"
redis_logfile: /var/log/redis/redis-server.log
redis_databases: 16
# Set to an empty set to disable persistence (saving the DB to disk).
redis_save:
  - 900 1
  - 300 10
  - 60 10000
redis_rdbcompression: "yes"
redis_dbfilename: dump.rdb
redis_dbdir: /var/lib/redis
redis_maxmemory: 0
redis_maxmemory_policy: "noeviction"
redis_maxmemory_samples: 5
redis_appendonly: "no"
redis_appendfsync: "everysec"
# Add extra include files for local configuration/overrides.
redis_includes: []
# Require authentication to Redis with a password.
redis_requirepass: ""
# Disable certain Redis commands for security reasons.
redis_disabled_commands: []
#  - FLUSHDB
#  - FLUSHALL
#  - KEYS
#  - PEXPIRE
#  - DEL
#  - CONFIG
#  - SHUTDOWN
#  - BGREWRITEAOF
#  - BGSAVE
#  - SAVE
#  - SPOP
#  - SREM
#  - RENAME
#  - DEBUG
redis_extra_config: ""

### Supervisor Service #########################################
supervisor_log_dir: /var/log/supervisor
supervisor_tmp_dir: /tmp
supervisor_started: true
supervisor_enabled: true
supervisor_nodaemon: true
supervisor_user: root

supervisor_unix_http_server_socket_path: "{{ supervisor_tmp_dir }}/supervisor.sock"

supervisor_inet_http_server_enable: false
supervisor_inet_http_server_port: '*:9001'

### Test URLs
test_solr_ckan_url: "http://{{ solr_host }}:{{ solr_port }}/solr/{{ solr_ckan_core_name }}"
test_redis_ckan_url: "redis://{{ redis_bind_interface }}:{{ redis_port }}/1"
test_ckan_sqlalchemy_url: "postgresql://{{ ckan_database.ckan_db_user }}:{{ ckan_database.ckan_db_password }}@{{ ckan_database.postgres_host }}/{{ ckan_database.ckan_db }}"
test_ckan_datastore_ro_url: "postgresql://{{ ckan_database.datastore_readonly_user }}:{{ ckan_database.datastore_readonly_password }}@{{ ckan_database.datastore_host }}/{{ ckan_database.ckan_datastore_db }}"
test_ckan_datastore_url: "postgresql://{{ ckan_database.ckan_db_user }}:{{ ckan_database.ckan_db_password }}@{{ ckan_database.datastore_host }}/{{ ckan_database.ckan_datastore_db }}"

### Other packages
proj_version: proj-9.1.1