version: '3'

services:
  ckan-server:
    container_name: ${CONTAINER_OS_NAME}
    build:
      context: .
      dockerfile: docker/${CONTAINER_OS}/${CONTAINER_OS}-${CONTAINER_OS_VERSION}/Dockerfile
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
          max-size: "100m"
          max-file: "10"
    ports:
      - ${CKAN_PORT_HOST}:${CKAN_PORT}
      - ${SSH_PORT_HOST}:${SSH_PORT}
      - ${NGINX_PORT_HOST}:${NGINX_PORT}
   