- name: Create Solr user
  include_role:
    name: solr
    tasks_from: solr_user.yml

- name: Install Java
  include_role:
    name: solr
    tasks_from: solr_install_java.yml

#TODO: Install Solr < 5.
- name: Install Solr version less than 5
  include_tasks: solr_install_pre5.yml
  when: "solr_version.split('.')[0] < '5'"

# Install Solr 5+.
- name: Install Solr version 5 or greater
  include_tasks: solr_install.yml
  when: "solr_version.split('.')[0] >= '5'"

- name: Setup Solr service
  include_role:
    name: solr
    tasks_from: solr_service.yml

- name: Setup Solr config
  include_role:
    name: solr
    tasks_from: solr_config.yml

- name: Setup CKAN config for Solr
  include_role:
    name: solr
    tasks_from: solr_config_ckan.yml

- name: Setup spatial config for Solr
  include_role:
    name: solr
    tasks_from: solr_config_spatial.yml

- name: Setup custom schema config for Solr
  include_role:
    name: solr
    tasks_from: solr_config_custom_schema.yml

- name: Restart Solr (RHEL 7+ workaround).
  command: service {{ solr_service_name }} restart
  ignore_errors: true

# Postinstall tasks
- name: Remove the downloaded Solr archive.
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    - "{{ solr_workspace }}/{{ solr_filename }}"

- name: Remove docs, if not needed.
  file:
    path: "{{ solr_dir }}/docs"
    state: absent
  when: solr_remove_cruft

- name: Remove example dir, if not needed.
  file:
    path: "{{ solr_dir }}/example"
    state: absent
  when:
    - solr_remove_cruft
    - solr_version.split('.')[0] >= '5'