- name: Stop solr
  command: service {{ solr_service_name }} stop
  failed_when: false
  when: solr_restart_handler_enabled

- name: Remove solr init.d file from {{ init_dir }}/
  file: 
    path: "{{ init_dir }}/{{ solr_service_name }}"
    state: absent
  become: true

- name: Remove solr init.d file
  file: 
    path: "{{ solr_dir }}/bin/init.d/solr"
    state: absent

- name: Copy {{ solr_service_name }} service
  template:
    src: "solr.service.j2"
    dest: "{{ systemd_dir }}/{{ solr_service_name }}.service"
    owner: root
    group: root
    mode: 0644

- name: Enable {{ solr_service_name }} service
  systemd:
    name: "{{ solr_service_name }}"
    daemon_reload: yes
    enabled: yes
  become: true
  register: solr_systemd

- name: Ensure {{ solr_service_name }} is started and enabled on boot if configured
  command:
    cmd: "systemctl enable {{ solr_service_name }}.service"
  become: true
  when: solr_systemd.status.UnitFileState == 'enabled-runtime'

- name: Restart "{{ solr_service_name }}"
  systemd: 
    name: "{{ solr_service_name }}"
    state: restarted
    enabled: true
  become: true
  when: solr_service_manage