- name: Check if Solr has been installed already.
  stat:
    path: "{{ solr_dir }}"
  register: solr_dir_status

- name: Set solr_filename for Solr >4.
  set_fact:
    solr_filename: "solr-{{ solr_version }}"
  when: "solr_version.split('.')[0] >= '4'"

- name: Set solr_mirror for Solr >9.
  set_fact:
    solr_project_mirror: "{{ solr_mirror }}/solr"
  when: solr_version.split('.')[0]|int >= 9

- name: Download Solr.
  get_url:
    url: "{{ solr_project_mirror }}/solr/{{ solr_version }}/{{ solr_filename }}.tgz"
    dest: "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    force: false
  when: solr_dir_status.stat.isdir is not defined
  register: solr_download_status

- name: Expand Solr.
  unarchive:
    src: "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    dest: "{{ solr_workspace }}"
    copy: false
  when: solr_download_status.changed
  tags: ['skip_ansible_lint']

- name: Show Java version
  command: java -version
  register: java_version
  changed_when: false

- name: Debug Java version
  debug:
    var: java_version.stderr

- name: Ensure service wrapper is installed for RHEL >9.
  package:
    name:
      - initscripts-service
      - chkconfig
    state: present
  when:
    - ansible_service_mgr == 'systemd'
    - ansible_os_family == 'RedHat'
    - ansible_distribution_version.split(".")[0] >= '9'

- name: Ensure service wrapper is installed for RHEL 7 & 8.
  package:
    name:
      - initscripts
      - chkconfig
    state: present
  when:
    - ansible_service_mgr == 'systemd'
    - ansible_os_family == 'RedHat'
    - ansible_distribution_version.split(".")[0] <= '8'

- name: Ensure service wrapper is installed for Debian-based distributions.
  package:
    name: init-system-helpers
    state: present
  when:
    - ansible_service_mgr == 'systemd'
    - ansible_os_family == 'Debian'

# We add '-n' to Solr versions beyond 6.3.0 to prevent autostart on install.
- name: Run Solr installation script.
  command: >
    {{ solr_workspace }}/{{ solr_filename }}/bin/install_solr_service.sh
    {{ solr_workspace }}/{{ solr_filename }}.tgz
    -i {{ solr_install_dir }}
    -d {{ solr_data }}
    -u {{ solr_user }}
    -s {{ solr_service_name }}
    -p {{ solr_port }}
    {{ (solr_version is version('6.3.0', '>=')) | ternary('-n','') }}
    {{ (solr_version is version('5.4.0', '>=')) | ternary('-f','') }}
    creates={{ solr_dir }}/bin/solr
  become: true
  register: solr_install_script_result
  environment:
    JAVA_HOME: "{{ java_home }}"

# Workaround for bug https://github.com/ansible/ansible-modules-core/issues/915.
- name: Ensure solr is stopped (RHEL 7+ workaround).
  command: service {{ solr_service_name }} stop
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_version.split(".")[0] >= '7'
    - solr_install_script_result.changed
  failed_when: false
  tags: ['skip_ansible_lint']

- name: Ensure {{ solr_data }} is owned by {{ solr_user }} and accessible.
  file:
    path: "{{ solr_data }}"
    owner: "{{ solr_user }}"
    group: "{{ solr_group }}"
    recurse: true
    mode: 0775
  when: solr_install_script_result.changed
