- name: Stop Solr
  service: 
    name: "{{ solr_service_name }}"
    state: stopped
    enabled: no

- name: Remove solr init.d file
  file: 
    path: "{{ solr_dir }}/bin/init.d/solr"
    state: absent

- name: Copy {{ solr_service_name }} service
  template:
    src: "solr.service.j2"
    dest: "{{ systemd_dir }}/{{ solr_service_name }}.service"
    owner: "{{ solr_user }}"
    mode: 0755

- name: Enable {{ solr_service_name }} service
  service:
    name: "{{ solr_service_name }}"
    enabled: yes
    masked: no
    daemon_reload: yes
    state: restarted

- name: Check {{ solr_service_name }} service status
  service:
    name: "{{ solr_service_name }}"
  register: solr_status

- debug:
    var: solr_status.status.Result

- name: Run systemd daemon_reload (RHEL 7+ workaround).
  service:
    name: "{{ solr_service_name }}"
    daemon_reload: true
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution_version.split(".")[0] >= '7'
    - solr_install_script_result.changed
  tags: ['skip_ansible_lint']

- name: Restart Solr
  become: true
  service: 
    name: "{{ solr_service_name }}"
    state: restarted
    enabled: yes

- name: Ensure Solr is started and enabled on boot if configured.
  become: true
  service:
    name: "{{ solr_service_name }}"
    state: "{{ solr_service_state }}"
    enabled: true
  when: solr_service_manage