- name: Install PostgreSQL client (RHEL/CentOS >= 8)
  dnf:
    name: "{{ postgresql_client_pkg }}"
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8

- name: Install PostgreSQL client (Debian/Ubuntu)
  apt:
    name: "{{ postgresql_deps_pkgs }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install PostgreSQL client (Arch Linux)
  pacman:
    name: "{{ postgresql_deps_pkgs }}"
    state: present
    update_cache: true
  when: ansible_os_family == "Archlinux"

- name: "Check if database {{ ckan_database.ckan_db }} exists"
  shell: |
    PGPASSWORD={{ ckan_database.ckan_db_password }} \
    psql -h {{ ckan_database.postgres_host }} -p {{ ckan_database.postgres_port }} -U {{ ckan_database.ckan_db_user }} -d {{ ckan_database.ckan_db }} -c '\q'
  register: ckan_db_exists
  failed_when: ckan_db_exists.rc != 0
  changed_when: false

- name: Debug ckan_db_exists
  debug:
    var: ckan_db_exists

- name: "Check if database {{ ckan_datastore.datastore_db }} exists"
  shell: |
    PGPASSWORD={{ ckan_database.ckan_db_password }} \
    psql -h {{ ckan_datastore.datastore_host }} -p {{ ckan_datastore.datastore_port }} -U {{ ckan_database.ckan_db_user }} -d {{ ckan_datastore.datastore_db }} -c '\q'
  register: datastore_db_exists
  failed_when: datastore_db_exists.rc != 0
  changed_when: false

- name: Debug datastore_db_exists
  debug:
    var: datastore_db_exists