- name: "Create CKAN user: ({{ ckan_database.ckan_db_user }})"
  postgresql_user:
    name: "{{ ckan_database.ckan_db_user }}"
    password: "{{ ckan_database.ckan_db_password }}"
    role_attr_flags: SUPERUSER 
    state: present

- name: "Create CKAN DB: ({{ ckan_database.ckan_db }})"
  postgresql_db:
    name: "{{ ckan_database.ckan_db }}"
    owner: "{{ ckan_database.ckan_db_user }}"
    encoding: UTF-8
    state: present

- name: "Grant {{ ckan_database.ckan_db_user }} user access to CKAN DB ({{ ckan_database.ckan_db }})"
  postgresql_privs:
    type: database
    database: "{{ ckan_database.ckan_db }}"
    roles: "{{ ckan_database.ckan_db_user }}"
    grant_option: false
    privs: all

- name: "Create datastore DB: ({{ ckan_database.datastore_db }}) readonly user"
  postgresql_user:
    name: "{{ ckan_datastore.datastore_readonly_user }}"
    password: "{{ ckan_datastore.datastore_readonly_password }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE,INHERIT,LOGIN,NOREPLICATION,NOBYPASSRLS
    state: present

- name: "Create datastore DB: ({{ ckan_datastore.datastore_db }}) own datastore read user ({{ ckan_datastore.datastore_readonly_user }})"
  postgresql_db:
    name: "{{ ckan_datastore.datastore_db }}"
    owner: "{{ ckan_datastore.datastore_readonly_user }}"
    encoding: UTF-8
    state: present