- name: Add custom pg_hba file 
  copy:
    src: "{{ role_path }}/files/pg_hba.conf"
    dest: "{{ postgres_dir }}/pg_hba.conf"
    owner: "{{ ckan_database.postgres_user }}"
    group: "{{ ckan_database.postgres_password }}"
    mode: 0600

- name: Restart the PostgresSQL service
  systemd:
    name: postgresql
    state: restarted