
- name: Virtualenv is installed and configured
  include_role:
    name: ckan
    tasks_from: ckan_virtualenv.yml

- name: Install Virtualenv pip constraints
  include_role:
    name: ckan
    tasks_from: ckan_config_pip_constraints.yml

- name: Install CKAN
  include_role:
    name: ckan
    tasks_from: ckan_install_ckan.yml

- name: Install CKAN extensions
  include_role:
    name: ckan
    tasks_from: ckan_install_ckan_exts.yml

- name: Setup CKAN config
  include_role:
    name: ckan
    tasks_from: ckan_config_ckan.yml

- name: Setup CKAN extensions config
  include_role:
    name: ckan
    tasks_from: ckan_config_exts.yml

- name: "Change owner and group of {{ ckan_dir }}/default to: {{ lookup('env','USER') }}"
  file:
    path: "{{ ckan_dir }}/default"
    owner: "{{ lookup('env','USER') }}"
    group: "{{ lookup('env','USER') }}"
    recurse: yes
  become: true
