# WTF CSRF token 
- name: Generate 
  command: "{{ ckan_virtualenv }}/bin/ckan config-tool {{ ckan_config_dir }}/ckan.ini 'WTF_CSRF_SECRET_KEY=$(python3 -c \"import secrets; print(secrets.token_urlsafe())\")'"
  become: true

# Beaker session secret and api_token.jwt secret are generated if not set in ckan.ini
- name: Generate beaker.session.secret
  command: '{{ ckan_virtualenv }}/bin/python3 -c "import secrets; print(secrets.token_urlsafe())"'
  register: beaker_session_secret

- name: Set beaker.session.secret in ckan.ini
  lineinfile:
    path: "{{ ckan_config_dir }}/ckan.ini"
    regexp: "^beaker.session.secret = default_secret_change_me"
    line: "beaker.session.secret = {{ beaker_session_secret.stdout }}"
  become: true
  when: beaker_session_secret.rc == 0

- name: Generate api_token.jwt secret
  command: '{{ ckan_virtualenv }}/bin/python3 -c "import secrets; print(\"string:\" + secrets.token_urlsafe())"'
  register: jwt_secret

- name: Set api_token.jwt.encode.secret in ckan.ini
  lineinfile:
    path: "{{ ckan_config_dir }}/ckan.ini"
    regexp: "^api_token.jwt.encode.secret = default_secret_change_me"
    line: "api_token.jwt.encode.secret = {{ jwt_secret.stdout }}"
  become: true
  when: jwt_secret.rc == 0

- name: Set api_token.jwt.decode.secret in ckan.ini
  lineinfile:
    path: "{{ ckan_config_dir }}/ckan.ini"
    regexp: "^api_token.jwt.decode.secret = default_secret_change_me"
    line: "api_token.jwt.decode.secret = {{ jwt_secret.stdout }}"
  become: true
  when: jwt_secret.rc == 0

- name: "Uncomment SMTP settings if {{ ckan_smpt_active | default(false) }} is true"
  block:
    - name: "Uncomment smtp.server"
      lineinfile:
        path: "{{ ckan_config_dir }}/ckan.ini"
        regexp: '^#smtp.server = {{ ckan_smtp_server }}'
        line: 'smtp.server = {{ ckan_smtp_server }}'
        state: present
      become: true

    - name: "Uncomment smtp.starttls"
      lineinfile:
        path: "{{ ckan_config_dir }}/ckan.ini"
        regexp: '^#smtp.starttls = {{ ckan_smpt_starttls }}'
        line: 'smtp.starttls = {{ ckan_smpt_starttls }}'
        state: present
      become: true

    - name: "Uncomment smtp.user"
      lineinfile:
        path: "{{ ckan_config_dir }}/ckan.ini"
        regexp: '^#smtp.user = {{ ckan_smtp_user }}'
        line: 'smtp.user = {{ ckan_smtp_user }}'
        state: present
      become: true

    - name: "Uncomment smtp.password"
      lineinfile:
        path: "{{ ckan_config_dir }}/ckan.ini"
        regexp: '^#smtp.password = {{ ckan_smtp_password }}'
        line: 'smtp.password = {{ ckan_smtp_password }}'
        state: present
      become: true

    - name: "Uncomment smtp.mail_from"
      lineinfile:
        path: "{{ ckan_config_dir }}/ckan.ini"
        regexp: '^#smtp.mail_from = {{ ckan_smtp_mail_from }}'
        line: 'smtp.mail_from = {{ ckan_smtp_mail_from }}'
        state: present
      become: true

    - name: "Uncomment smtp.reply_to"
      lineinfile:
        path: "{{ ckan_config_dir }}/ckan.ini"
        regexp: '^#smtp.reply_to = {{ ckan_smtp_reply_to }}'
        line: 'smtp.reply_to = {{ ckan_smtp_reply_to }}'
        state: present
      become: true

    - name: "Uncomment email_to"
      lineinfile:
        path: "{{ ckan_config_dir }}/ckan.ini"
        regexp: '^#email_to = {{ ckan_email_to }}'
        line: 'email_to = {{ ckan_email_to }}'
        state: present
      become: true

    - name: "Uncomment error_email_from"
      lineinfile:
        path: "{{ ckan_config_dir }}/ckan.ini"
        regexp: '^#error_email_from = {{ ckan_error_email_from }}'
        line: 'error_email_from = {{ ckan_error_email_from }}'
        state: present
      become: true

  when: ckan_smpt_active | default(false)