- name: "Create CKAN virtualenv directory {{ ckan_virtualenv }}"
  file:
    path: "{{ ckan_virtualenv }}"
    state: directory
    mode: '0755'
  become: true

- name: "Create CKAN config directory {{ ckan_config_dir }}"
  file:
    path: "{{ ckan_config_dir }}"
    state: directory
    mode: '0755'
  become: true

- name: "Change owner and group of {{ ckan_virtualenv }} to: {{ ckan_user }}"
  file:
    path: "{{ ckan_virtualenv }}"
    owner: "{{ ckan_user }}"
    group: "{{ ckan_group }}"
    recurse: yes
  become: true

- name: "Change owner and group of {{ ckan_config_dir }} to: {{ ckan_user }}"
  file:
    path: "{{ ckan_config_dir }}"
    owner: "{{ ckan_user }}"
    group: "{{ ckan_group }}"
    recurse: yes
  become: true

- name: Create virtualenv for CKAN
  become: true
  become_user: "{{ ckan_user }}"
  command: "python3 -m venv {{ ckan_virtualenv }}"

- name: Install setuptools and wheel
  pip:
    name:
      - setuptools
      - wheel
    virtualenv: "{{ ckan_virtualenv }}"
  become: true
  become_user: "{{ ckan_user }}"

- name: Upgrade pip in virtualenv
  pip:
    name:
      - pip
    extra_args: --upgrade
    virtualenv: "{{ ckan_virtualenv }}"
  become: true
  become_user: "{{ ckan_user }}"

- name: Ensure {{ ckan_virtualenv }}/src exists
  file:
    path: "{{ ckan_virtualenv }}/src"
    state: directory
  become: true
  become_user: "{{ ckan_user }}"

- name: Find directories in {{ ckan_virtualenv }}/src that are not 'ckan' or 'ckan-pycsw'
  find:
    paths: "{{ ckan_virtualenv }}/src"
    file_type: directory
    excludes: ['ckan', 'ckan-pycsw']
  register: dirs_to_remove

- name: Remove directories in {{ ckan_virtualenv }}/src that are not 'ckan'
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ dirs_to_remove.files }}"
  become: true
  become_user: "{{ ckan_user }}"