- name: Update package versions in CKAN requirements
  lineinfile:
    path: "{{ ckan_src_dir }}/ckan/requirements.txt"
    regexp: "^{{ item.split('==')[0] }}=="
    line: "{{ item }}"
  loop: "{{ ckan_constraints.stdout_lines }}"
  when: ckan_constraints is defined and ckan_constraints.stdout_lines | length > 0

- name: Install CKAN requirements
  become: true
  become_user: "{{ ckan_user }}"
  pip:
    requirements: "{{ ckan_src_dir }}/ckan/requirements.txt"
    virtualenv: "{{ ckan_virtualenv }}"
    state: present

- name: Install CKAN development requirements
  become: true
  become_user: "{{ ckan_user }}"
  pip:
    requirements: "{{ ckan_src_dir }}/ckan/dev-requirements.txt"
    virtualenv: "{{ ckan_virtualenv }}"
    state: present

- name: Run setup.py develop for Python3 CKAN
  become: true
  become_user: "{{ ckan_user }}"
  pip:
    name: "file://{{ ckan_src_dir }}/ckan"
    virtualenv: "{{ ckan_virtualenv }}"
    editable: true

- name: Get CKAN Version
  command: '{{ ckan_virtualenv }}/bin/python3 -c "import ckan; print(ckan.__version__)"'
  register: ckan_version
