- name: Check Solr connection
  uri:
    url: "{{ test_solr_ckan_url }}/schema/name?wt=json"
    return_content: yes
  register: solr_response
  until: solr_response.status == 200
  retries: 8
  delay: 10

- name: Check Solr schema
  assert:
    that: "'ckan' in solr_response.json.name"
    fail_msg: "Successfully connected to Solr, but CKAN schema not found"
    success_msg: "Successfully connected to Solr and CKAN schema loaded"

- name: "Check main DB ({{ ckan_database.ckan_db }}) connection"
  postgresql_ping:
    db: "{{ ckan_database.ckan_db }}"
    login_host: "{{ ckan_database.postgres_host }}"
    login_user: "{{ ckan_database.ckan_db_user }}"
    login_password: "{{ ckan_database.ckan_db_password }}"
  register: db_conn
  until: db_conn.is_available
  retries: 5
  delay: 10

- name: "Check datastore DB ({{ ckan_database.ckan_db }}) connection"
  postgresql_ping:
    db: "{{ ckan_datastore.datastore_db }}"
    login_host: "{{ ckan_datastore.datastore_host }}"
    login_user: "{{ ckan_database.ckan_db_user }}"
    login_password: "{{ ckan_database.ckan_db_password }}"
  register: db_conn
  until: db_conn.is_available
  retries: 5
  delay: 10