- name: "Ensure {{ solr_group }} exists."
  group: "name={{ solr_group }} state=present"

- name: "Ensure user: {{ solr_user }} exists."
  user:
    name: "{{ solr_user }}"
    state: present
    group: "{{ solr_group }}"