- name: Install and setup Supervisor
  include_role:
    name: supervisor
    tasks_from: supervisor_install.yml

- name: Setup CKAN workers
  include_role:
    name: supervisor
    tasks_from: ckan_workers.yml

- name: Ensure Supervisor is enabled at boot (if configured).
  service:
    name: supervisord
    enabled: true
  when: supervisor_enabled

- name: "Change owner and group of {{ ckan_log_dir }} to {{ ckan_user }}"
  file:
    path: "{{ ckan_log_dir }}"
    owner: "{{ ckan_user }}"
    group: "{{ ckan_group }}"
    recurse: yes
  become: true

- name: Reload systemd manager configuration
  become: true
  command: systemctl daemon-reload