- name: Install supervisor
  dnf:
    name: supervisor
    state: present
    update_cache: yes

- name: Ensure Supervisor log dir exists.
  file:
    path: "{{ supervisor_log_dir }}"
    state: directory
    mode: 0755