---

- name: Install PostgreSQL
  apt:
    name: ['postgresql-12', 'postgresql-contrib', 'postgis', 'python3-psycopg2']
    state: present

- name: Add custom pg_hba file 
  copy:
    src: files/pg_hba.conf
    dest: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0600

- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted
    enabled: yes

- name: Create PostgreSQL User
  postgresql_user:
    name: "{{ ckan_database.ckan_db_user }}"
    password: "{{ ckan_database.ckan_db_password }}"
    role_attr_flags: SUPERUSER 
    state: present

- name: Create PostgreSQL Database
  postgresql_db:
    name: "{{ ckan_database.ckan_db }}"
    owner: "{{ ckan_database.ckan_db_user }}"
    encoding: UTF-8
    state: present

- name: Grant db user access to db
  postgresql_privs:
    type: database
    database: "{{ ckan_database.ckan_db }}"
    roles: "{{ ckan_database.ckan_db_user }}"
    grant_option: false
    privs: all

- name: Create datastore readonly user
  postgresql_user:
    name: "{{ ckan_datastore.datastore_readonly_user }}"
    password: "{{ ckan_datastore.datastore_readonly_password }}"
    role_attr_flags: NOSUPERUSER,NOCREATEDB,NOCREATEROLE,INHERIT,LOGIN,NOREPLICATION,NOBYPASSRLS
    state: present

- name: Create datastore db own datastore read user
  postgresql_db:
    name: "{{ ckan_datastore.datastore_db }}"
    owner: "{{ ckan_datastore.datastore_readonly_user }}"
    encoding: UTF-8
    state: present