- name: Define redis_package.
  set_fact:
    redis_package: "{{ __redis_package }}"
  when: redis_package is not defined

- name: Ensure Redis configuration dir exists.
  file:
    path: "{{ redis_conf_path | dirname }}"
    state: directory
    mode: 0755

- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: "{{ redis_conf_mode }}"
  notify: restart redis

# Setup/install tasks.
- name: "Setup/install tasks for {{ ansible_os_family }}"
  include_tasks: "redis_install_{{ ansible_os_family | lower }}.yml"
  when: ansible_os_family in redis_os_supported

- name: Ensure Redis is running and enabled on boot.
  service: 
   name: "{{ redis_daemon }}"
   state: started
   enabled: yes