- name: "Ensure Redis {{ redis_version}} is installed."
  package:
    name: "{{ redis_package }}-{{ redis_version }}"
    state: present
    enablerepo: "{{ redis_enablerepo | default(omit, true) }}"