- name: Install required collections from ansible-galaxy or local tar.gz
  block:
    - name: Attempt to install collections from ansible-galaxy
      command: ansible-galaxy collection install "{{ item }}"
      loop: "{{ ansible_collections }}"
      register: galaxy_install
      ignore_errors: true

    - name: Find local tar.gz file for each collection if ansible-galaxy install fails
      find:
        paths: "{{ role_path }}/files/collections"
        patterns: "{{ item | replace('.', '-') }}-*.tar.gz"
      register: found_files
      loop: "{{ ansible_collections }}"
      when: galaxy_install is failed

    - name: Install collection from found tar.gz file
      command: ansible-galaxy collection install "{{ item.files | map(attribute='path') | first }}"
      loop: "{{ found_files.results }}"
      when: 
        - "'files' in item"
        - "item.files | length > 0"
        - galaxy_install is failed
  tags: always