### Packages: https://rhel.pkgs.org/8

### Supervisor
supervisord_bin_path: /usr/bin/supervisord
supervisorctl_bin_path: /usr/bin/supervisorctl
supervisord_conf_file: /etc/supervisord.conf
supervisord_workers_dir : /etc/supervisord.d
supervisord_service: supervisord

### Redis
__redis_package: redis
redis_daemon: redis
redis_conf_path: /etc/redis.conf
redis_conf_mode: 0644

### PostgreSQL
postgres_version: 15

### Python
python_pkg: python39
python_bin_path: /usr/bin/python3.9

### Proj
proj_gtest_pkg: gcc-c++

### Java
openjdk_pkg: java-11-openjdk
java_bin_path: /usr/lib/jvm

### systemd
systemd_dir: /lib/systemd/system

### service
init_dir: /etc/init.d