# Enable extensions
- name: Enable ckanext-scheming plugin
  become: true
  lineinfile:
    path: "{{ ckan_config_dir}}/ckan.ini"
    backrefs: yes
    regexp: ^(ckan\.plugins = .* recline_view).*$
    line: \1 scheming_datasets scheming_groups scheming_organizations