--- 

### Ansible connection  #########################################
## If you are running the playbook on the same machine, you can use the "local" connection instead of "ssh"
ansible_connection: ssh

### Host  #########################################
server_name: production
ansible_host: 192.168.68.109
ansible_user: ckan
ansible_port: 8022
ansible_ssh_pass: ckan

### CKAN variables #########################################
ckan_version: ckan-2.9.10
ckan_site_name: youckanurl.com
ckan_site_url: http://{{ ckan_site_name }}
ckan_site_title: Your-Company Data Portal
ckan_site_description: "Sample description for Your-Company's data management e.t.c."

### Database variables #########################################
postgres_version: 15
ckan_database: {
  ckan_db_user: "ckan_portal_user",
  ckan_db_password: ">C4fMsJb.*Va-rV2",
  ckan_db: "ckan_portal_db",
  postgres_host: "localhost",
}

ckan_datastore: {
  datastore_readonly_user: "ckan_datastore_user",
  datastore_readonly_password: "DC4fMsJb+",
  datastore_db: "ckan_datastore_db",
  datastore_host: "localhost",
}

### Solr Service #########################################
solr_version: 9
ckan_solr_core_name: ckan

