
  # If using private repositories a SSH keypair should be placed in the provisioning/files/
  # directory. The filenames of the keypair files must begin with id_ (e.g. id_rsa + id_rsa.pub).
  - name: Get filenames of files of SSH keypair to copy
    find:
      paths: files/
      patterns: ^id_
      use_regex: yes
    register: keypair_filenames
    delegate_to: localhost

  - name: Check if keypair files available
    fail:
      msg: No keypair files present in provisioning/files/!
    when: not keypair_filenames.files

  - name: Copy SSH keys
    become: true
    copy:
      src: "{{ item.path }}"
      dest: /root/.ssh/
      mode: preserve
    with_items:
      - "{{ keypair_filenames.files }}"

  - name: Add SSH fingerprint of github.com to known_hosts
    become: true
    shell: ssh-keyscan -H github.com >> /root/.ssh/known_hosts